# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfluenceCli < Formula
  desc "CLI for Confluence Cloud API, optimized for AI agents"
  homepage "https://github.com/Prisma-Labs-Dev/confluence-cli"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.2/confluence-cli_darwin_amd64.tar.gz"
      sha256 "793bc2885ae183fcaba0747a9a0b5677fb1618670f0ef519f7eb3219ea8f58bd"

      def install
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.2/confluence-cli_darwin_arm64.tar.gz"
      sha256 "be6ac0b5d79ce0d1d32bb163d1499ce1217dedd7f4f1eaff65e040560519d7b8"

      def install
        bin.install "confluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.2/confluence-cli_linux_amd64.tar.gz"
      sha256 "2907e0610ba557cf661de3b52cd577174cc04dc8a700ae08bd2ddede236477d1"
      def install
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.2/confluence-cli_linux_arm64.tar.gz"
      sha256 "b750875b988f84da2827a788548829586cb524ce70922ae629be25428d23ec24"
      def install
        bin.install "confluence"
      end
    end
  end

  test do
    system "#{bin}/confluence", "version"
  end
end
