# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfluenceCli < Formula
  desc "CLI for Confluence Cloud API, optimized for AI agents"
  homepage "https://github.com/Prisma-Labs-Dev/confluence-cli"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.0/confluence-cli_darwin_amd64.tar.gz"
      sha256 "d00e48bbb42a6c9a8847607f4ee2be91f70d5b81117a5993af434e77e01397bc"

      def install
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.0/confluence-cli_darwin_arm64.tar.gz"
      sha256 "f16483cbb219e7c0520c9bc065f7bf901f4b1f07e87cb93945ee0128ec516945"

      def install
        bin.install "confluence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.0/confluence-cli_linux_amd64.tar.gz"
      sha256 "4540561b56062e049412a1bdaae582d8fca0ace0ec0a79862ff38f4aa1fb3834"
      def install
        bin.install "confluence"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Prisma-Labs-Dev/confluence-cli/releases/download/v0.3.0/confluence-cli_linux_arm64.tar.gz"
      sha256 "94cebdbbb6574f16f4846025a237784f70885074368dc61c4f97d1bd808af0ba"
      def install
        bin.install "confluence"
      end
    end
  end

  test do
    system "#{bin}/confluence", "version"
  end
end
